/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageDeskRouteImport } from './routes/triage-desk'
import { Route as TopHeroesRouteImport } from './routes/top-heroes'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as NeighborhoodNetRouteImport } from './routes/neighborhood-net'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CivicWalletRouteImport } from './routes/civic-wallet'
import { Route as AiIntakeRouteImport } from './routes/ai-intake'
import { Route as IndexRouteImport } from './routes/index'

const TriageDeskRoute = TriageDeskRouteImport.update({
  id: '/triage-desk',
  path: '/triage-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TopHeroesRoute = TopHeroesRouteImport.update({
  id: '/top-heroes',
  path: '/top-heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodNetRoute = NeighborhoodNetRouteImport.update({
  id: '/neighborhood-net',
  path: '/neighborhood-net',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicWalletRoute = CivicWalletRouteImport.update({
  id: '/civic-wallet',
  path: '/civic-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntakeRoute = AiIntakeRouteImport.update({
  id: '/ai-intake',
  path: '/ai-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-intake': typeof AiIntakeRoute
  '/civic-wallet': typeof CivicWalletRoute
  '/login': typeof LoginRoute
  '/neighborhood-net': typeof NeighborhoodNetRoute
  '/roster': typeof RosterRoute
  '/top-heroes': typeof TopHeroesRoute
  '/triage-desk': typeof TriageDeskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-intake': typeof AiIntakeRoute
  '/civic-wallet': typeof CivicWalletRoute
  '/login': typeof LoginRoute
  '/neighborhood-net': typeof NeighborhoodNetRoute
  '/roster': typeof RosterRoute
  '/top-heroes': typeof TopHeroesRoute
  '/triage-desk': typeof TriageDeskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-intake': typeof AiIntakeRoute
  '/civic-wallet': typeof CivicWalletRoute
  '/login': typeof LoginRoute
  '/neighborhood-net': typeof NeighborhoodNetRoute
  '/roster': typeof RosterRoute
  '/top-heroes': typeof TopHeroesRoute
  '/triage-desk': typeof TriageDeskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-intake'
    | '/civic-wallet'
    | '/login'
    | '/neighborhood-net'
    | '/roster'
    | '/top-heroes'
    | '/triage-desk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-intake'
    | '/civic-wallet'
    | '/login'
    | '/neighborhood-net'
    | '/roster'
    | '/top-heroes'
    | '/triage-desk'
  id:
    | '__root__'
    | '/'
    | '/ai-intake'
    | '/civic-wallet'
    | '/login'
    | '/neighborhood-net'
    | '/roster'
    | '/top-heroes'
    | '/triage-desk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiIntakeRoute: typeof AiIntakeRoute
  CivicWalletRoute: typeof CivicWalletRoute
  LoginRoute: typeof LoginRoute
  NeighborhoodNetRoute: typeof NeighborhoodNetRoute
  RosterRoute: typeof RosterRoute
  TopHeroesRoute: typeof TopHeroesRoute
  TriageDeskRoute: typeof TriageDeskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage-desk': {
      id: '/triage-desk'
      path: '/triage-desk'
      fullPath: '/triage-desk'
      preLoaderRoute: typeof TriageDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-heroes': {
      id: '/top-heroes'
      path: '/top-heroes'
      fullPath: '/top-heroes'
      preLoaderRoute: typeof TopHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood-net': {
      id: '/neighborhood-net'
      path: '/neighborhood-net'
      fullPath: '/neighborhood-net'
      preLoaderRoute: typeof NeighborhoodNetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic-wallet': {
      id: '/civic-wallet'
      path: '/civic-wallet'
      fullPath: '/civic-wallet'
      preLoaderRoute: typeof CivicWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intake': {
      id: '/ai-intake'
      path: '/ai-intake'
      fullPath: '/ai-intake'
      preLoaderRoute: typeof AiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiIntakeRoute: AiIntakeRoute,
  CivicWalletRoute: CivicWalletRoute,
  LoginRoute: LoginRoute,
  NeighborhoodNetRoute: NeighborhoodNetRoute,
  RosterRoute: RosterRoute,
  TopHeroesRoute: TopHeroesRoute,
  TriageDeskRoute: TriageDeskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
